### ISSUE TITLE
Post transclusions should be returned as an array 

### ISSUE THREAD

**Issue by cbroms** [rainflame/pith#17]
Currently, the backend sends a map of transcluded IDs for every post that has transclusions. This should be changed to an array so the order transclusions appear is preserved. 

Currently:
```json
{
    "k5rxb5t2owyu": "hello, this is a post",
    "ocy83cof8964": "some idea"
}
```

Ideally:
```json
[
    { "id": "k5rxb5t2owyu", "pith": "hello, this is a post" },
    { "id": "ocy83cof8964", "pith": "some idea" }
]
```

**Comment by slz4025** [comment]
Might require changing unit schema to save transclusions directly...do later.
