### ISSUE TITLE
Search with multiple filters.

### ISSUE THREAD

**Issue by slz4025** [rainflame/pith#24]
- Must always filter on current board.
- Use keywords. 
- Can also search within current discussion. Search within just chat or block units.
- For discussion units, can filter on author/time.

**Comment by slz4025** [comment]
The discussion should have its own search, which only searches among the chat units (maybe we can mark which units are pinned). This should be done on frontend.

The board should have its own search. The search can be done on the backend in preparation for larger loads, perhaps.

**Comment by cbroms** [comment]
Search for the discussion should place results above the text box. Something similar should work for board units as well.

**Comment by slz4025** [comment]
Also when copying ID, should get the id in the form of `[[unit_id]]`. When a person types `[[`, this begins the search for a given unit, which they then close with `]]`.

**Comment by slz4025** [comment]
Done on backend.
