### ISSUE TITLE
Handle deleting a board unit

### ISSUE THREAD

**Issue by cbroms** [rainflame/pith#25]
How should we deal with this? Might be able to automatically unfocus the unit from any attached discussions... Alternatively could prevent deleting while discussions are attached.

**Comment by slz4025** [comment]
Simple solution. Perhaps instead of deleting a board unit, we mark it with a "hide". Then, in rendering it for transclusions, focus, links, we can choose whether we want to show it or not. 
If hidden, it will be marked as hidden and not part of board units.
