### ISSUE TITLE
Participant count continuously increments

### ISSUE THREAD

**Issue by cbroms** [rainflame/pith#31]

**Comment by cbroms** [comment]
I'm guessing this is because the backend is not correctly handling the disconnect event

**Comment by slz4025** [comment]
Will need to replicate this on the dev by having people join and leave by closing out.

**Comment by slz4025** [comment]
Person 1 joins, yielding 1 participants.
Person 2 joins, yielding 2 participants.
Person 2 refreshes, yielding 3 participants.

**Comment by slz4025** [comment]
fixed
