### ISSUE TITLE
Rework pinned unit section

### ISSUE THREAD

**Issue by cbroms** [rainflame/pith#33]
- Rename to "summary" 
- Increase width, reducing chat and board width to accommodate
- Increase height so it takes 2/3 rather than 1/2 of vertical space

**Comment by slz4025** [comment]
For increasing width, keep the dimensions of the discussion as it is currently. But split it down center so chat is on left, pinned/focused is on right. It would be good if units are the same width in chat or pinned (summary) so they both have importance/attention.

**Comment by slz4025** [comment]
We will also need to consider how big the board should be, especially with the 2D situation.

**Comment by slz4025** [comment]
Eventually make sections adjustable.
