### ISSUE TITLE
Push updates to the board 

### ISSUE THREAD

**Issue by cbroms** [rainflame/pith#34]
Rather than having the client constantly creating requests to refresh the board, have the server push updates to clients every 10 seconds or so. Only send updates if there's new content. This is much more efficient as it removes unnecessary requests from the client and sends *just* the data that's been changed.

**Comment by slz4025** [comment]
Want to avoid many requests. Above approach better if there are few updates. May require some timer mechanism, like we had before. May require the creation of a board room for an emit.

**Comment by slz4025** [comment]
@cbroms Need you to have the top-level index render the list of boards created. This will be good anyway and will help debug this feature.
New branch on `server_update`.

**Comment by slz4025** [comment]
Mostly implemented this. Could make it more efficient by only sending when there is new data and participants to receive it.

**Comment by slz4025** [comment]
Actually should probably just check if the message is empty. If it's not, someone is probably in the board anyway.
