### ISSUE TITLE
Typing indicators

### ISSUE THREAD

**Issue by cbroms** [rainflame/pith#35]
We need something. Probably not "jim is typing...", but perhaps just some little animated ellipses when typing is happening. 

This will require creating some client logic to determine if someone is typing and sending start and stop events to the backend. The backend can then send updates to all clients to indicate typing is or is not taking place.

**Comment by cbroms** [comment]
Actually, it could be pretty nice if the number of ellipses represents the number of people typing. So you have one little bouncing dot for one person, two for two, and so on. It's a visual representation of "noise" without explicitly telling you *who* is typing, which is a bit annoying as the person typing.

**Comment by slz4025** [comment]
Consider more in-depth later.

**Comment by slz4025** [comment]
Put in new branch, `typing_indicators` as possible design feature.

**Comment by slz4025** [comment]
This is a listening mechanism. How does it compare to say, somebody clicking on posts they have acknowledged? Or other mechanisms?

**Comment by slz4025** [comment]
So need new backend methods.
`typingStart(participant)`, `typingStop(participant)`. Each will send the participants to everyone else. The store will have an array of who is typing, call it `typers`. Then the frontend can decide how to use this information to render.

**Comment by slz4025** [comment]
Made draft of backend. Connect to frontend and test system.

**Comment by cbroms** [comment]
This isn't sending to anyone other than the person who's typing

https://github.com/rainflame/pith/blob/b24ee9004a5ef88be888a8788e5f57eac5d18af4/backend/src/app.py#L391-L401

**Comment by slz4025** [comment]
Fixed. Please put "typing..." above textbox.
