### ISSUE TITLE
Can't copy to the clipboard when connecting insecurely

### ISSUE THREAD

**Issue by slz4025** [rainflame/pith#43]

**Comment by cbroms** [comment]
What does this mean?

**Comment by slz4025** [comment]
At least before, clicking the # didn't always copy the id.

**Comment by slz4025** [comment]
Transclusion wasn't rendering. Had to do with clipboard not working if not on localhost or https.

**Comment by cbroms** [comment]
We're using the [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API), which is only available on sites served over https (localhost is ok too). 

At the moment there are no plans to provide compatibility with IE or sites served over unsecured http. If you're connecting to an instance with its IP address, use a self-signed certificate or configure your browser to trust the site.
