### ISSUE TITLE
Render board in 2D

### ISSUE THREAD

**Issue by slz4025** [rainflame/pith#47]
Existing solutions, like in React, are too big, or others are too specific. 
May need to cook-up something ourselves.

Need:
- seemingly infinite space, with origin (in center of div), and maybe bounding box
- panning => library?
- zoom in/out => library?
- rendering of basic shapes, like rectangles and arrows (arrows could get messy!)
- drag and drop, but on a grid => will have to worry a bit about arrow rendering

How do existing methods do it, like mind-mappers or design spaces? Excalidraw, kinopio.club, Figma.
Excalidraw and others use a more heavy solution, which feels rather slow.

For now, maybe use kinopio solution. Origin is at top-left, uses native scrollbars and zooming. For "arrows", there is a line that draws from one point to another. This is a pretty smart idea. The nodes are always rendered above the lines. The lines don't have directionality. Maybe instead of having an arrow point at the end, the line itself has chevrons on it indicating direction. Also, requires dragging to make line. Would be nicer to do a click-click.

**Comment by slz4025** [comment]
1) First, hammer out a working prototype of drawing elements on front-end.
2) Consider abstractions needed to render properly that should be stored on backend, and functionality that goes along with it.
3) Refine.

**Comment by cbroms** [comment]
For panning and zooming, [panzoom](https://github.com/anvaka/panzoom) seems promising. It seems [small enough](https://bundlephobia.com/result?p=panzoom@9.4.1).

**Comment by slz4025** [comment]
Also, we want some key buttons to allow people to do common operations. I.e. make a unit, make a link, make a beam, group together units under a new set-unit, etc.

**Comment by slz4025** [comment]
We also want a very nice visual way to focus on a particular unit. We should be able to get a view of what sets it is in, what units are within it, what links it has. It would be great if from this focused view, we could click on the "parents", "children", and "linked units" to focus on them, thereby creating a chain of hierarchical-like or network-like movement.

**Comment by slz4025** [comment]
Implemented backend in `2d_board`. Now frontend needs to use `full_size` in board's store to render element and use `move_unit`.
